version: "3"
services:
  develop:
    build: .
    container_name: doc-writer
    environment:
      PORT: 7400
      NODE_PATH: app/src
      NODE_ENV: develop
    command: develop
    volumes:
      - ./app:/opt/doc-writer/app
