apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: {name}
  name: {name}
spec:
  revisionHistoryLimit: 0
  template:
    metadata:
      labels:
        name: {name}
        role: doc-writer
    spec:
      containers:
      - name: {name}
        image: vizzuality/{name}
        imagePullPolicy: Always
        resources:
          requests:
            memory: "0Mi"
            cpu: "0m"
        args:
          - start
        env:
          - name: NODE_ENV
            value: staging
          - name: NODE_PATH
            value: app/src
          - name: ELASTIC_URL
            valueFrom:
                secretKeyRef:
                  name: dbsecrets
                  key: ELASTIC_URI
          - name: RABBITMQ_URL
            valueFrom:
                secretKeyRef:
                  name: dbsecrets
                  key: RABBITMQ_URI
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: role
                    operator: In
                    values:
                      - doc-writer
              topologyKey: "kubernetes.io/hostname"

      restartPolicy: Always
