apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: {name}
  name: {name}
spec:
  revisionHistoryLimit: 0
  template:
    metadata:
      labels:
        name: {name}
        role: doc-writer
    spec:
      containers:
      - name: {name}
        image: vizzuality/{name}
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "0.5"
            memory: "256M"
          limits:
            cpu: "1"
            memory: "512M"
        args:
          - start
        env:
          - name: PORT
            value: "7400"
          - name: NODE_ENV
            value: staging
          - name: NODE_PATH
            value: app/src
          - name: ELASTIC_URL
            valueFrom:
                secretKeyRef:
                  name: dbsecrets
                  key: ELASTIC_URI
          - name: RABBITMQ_URL
            valueFrom:
                secretKeyRef:
                  name: dbsecrets
                  key: RABBITMQ_URI
        ports:
            - containerPort: 7400
        readinessProbe:
          httpGet:
            scheme: HTTP
            path: /healthcheck
            port: 7400
          initialDelaySeconds: 15
          timeoutSeconds: 5
          periodSeconds: 15
        livenessProbe:
          httpGet:
            scheme: HTTP
            path: /healthcheck
            port: 7400
          failureThreshold: 3
          initialDelaySeconds: 15
          timeoutSeconds: 5
          periodSeconds: 15
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: role
                    operator: In
                    values:
                      - doc-writer
              topologyKey: "kubernetes.io/hostname"

      restartPolicy: Always
