apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {name}
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: {name}
  minReplicas: 1
  maxReplicas: 50
  metrics:
    - type: External
      external:
        metricName: "custom.googleapis.com|rabbitmq_queue_messages_ready"
        metricSelector:
          matchLabels:
            metric.labels.queue: DOC-DATA
        targetValue: 20
