apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: doc-writer
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: doc-writer
  minReplicas: 4
  maxReplicas: 4
